### ISSUE TITLE
It seems that params are not set properly

### ISSUE THREAD

**Issue by mahmoudparsian** [bluebreezecf/SparkJobServerClient#1]
In 

public class SparkJobServerClientTest {
...
            params.put(ISparkJobServerClientConstants.PARAM_MEM_PER_NODE, "10");
            params.put(ISparkJobServerClientConstants.PARAM_NUM_CPU_CORES, "512m"); 

it should be:
            params.put(ISparkJobServerClientConstants.PARAM_MEM_PER_NODE, "512m" );
            params.put(ISparkJobServerClientConstants.PARAM_NUM_CPU_CORES,  "10"); 

best regards,
Mahmoud Parsian

**Comment by schermannj** [comment]
Yes, I saw this mistake, thank you.

**Comment by bluebreezecf** [comment]
@mahmoudparsian 

The mistakes of the parameters usage you mentioned have been fixed, so i will close this issue. 
Please refresh to check out it. Thanks a lot for your kind suggests.

Best regards,
Jianwei Shi
