### ISSUE TITLE
Can not resolve mehtod client.stop()

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [bluebreezecf/SparkJobServerClient#10]
I try to run the code In How to use part,

evertthing is ok but can not find client 's  "stop" method

**Comment by bluebreezecf** [comment]
@feiwofeifeixiaowo  
Hi bro, thanks for your concerns of the sample code.
I have refreshed the README according to the latest implememtation(https://github.com/bluebreezecf/SparkJobServerClient/commit/44ce3e66365d2412487a4acf2746ecd2730d005f).
The issue you mentioned has been fixed, please check it out.

**Comment by feiwofeifeixiaowo** [comment]
@bluebreezecf 
Thanks for your reply.
It works well now.

**Comment by bluebreezecf** [comment]
@feiwofeifeixiaowo 
You are welcome man.
Appreciate for your reply.
