### ISSUE TITLE
Is there way to run job with config or data file?

### ISSUE THREAD

**Issue by yatszhash** [bluebreezecf/SparkJobServerClient#14]
Is there way to run job with config or data file?

Now, there isn't way to run job directly with a file or a input stream.
However, in actual, frequently we'd like  to run job with config or data file.

Shall we add runJob method with a file or input stream to SparkJobServiceClientImpl?

**Comment by bluebreezecf** [comment]
@yatszhash Yeap bro， your idea is cool and your solution seems good.
Let's check into the details of pr and make it  done.

**Comment by bluebreezecf** [comment]
@yatszhash  Thanks for your PR.
By the way, i suggest you to fill in your personal profile of the github account. By finishing this, the github server will recognize you as a valid user, your commits will be presented properly, and you will be listed in the contributor list (https://github.com/bluebreezecf/SparkJobServerClient/graphs/contributors).
Your contributions should be presented explicitly.
