### ISSUE TITLE
Maven Central packaging 

### ISSUE THREAD

**Issue by calvin-pietersen** [bluebreezecf/SparkJobServerClient#17]
Can we look at uploading to Maven Central? 

I was previously using Codegerm's  fork https://mvnrepository.com/artifact/com.github.codegerm/spark-job-server-client. However, it is not up to date.

**Comment by bluebreezecf** [comment]
@calvin-pietersen  Thanks for your kind advice. Your idea is great and I think if the original SparkJobServerClient upload to Maven Central, it will help people more easily.

I will do it, we will see.

**Comment by calvin-pietersen** [comment]
@bluebreezecf is there any progress with this? Do you need help?

**Comment by bluebreezecf** [comment]
@calvin-pietersen 
This issue is in the progress, thanks for your concerns.

**Comment by bluebreezecf** [comment]
@calvin-pietersen 
The original SparkJobServerClient can be downloaded from [repo1.maven.org/maven2](http://repo1.maven.org/maven2/com/bluebreezecf/spark-job-server-client/1.0.0/)
And you also can search it in [search.maven.org](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-job-server-client%22).

Thanks for your kind and nice advice, from now on, everyone can use the spark-jobs-server-client up to date without compiling by himself.

So I close this issue

**Comment by calvin-pietersen** [comment]
Thanks @bluebreezecf!
