### ISSUE TITLE
Cannot use spring boot jar.original 

### ISSUE THREAD

**Issue by elzinko** [bluebreezecf/SparkJobServerClient#20]
https://github.com/bluebreezecf/SparkJobServerClient/blob/6401d79f1a3387967a210f9da85a680269f7bb99/src/main/java/com/bluebreezecf/tools/sparkjobserver/api/SparkJobServerClientImpl.java#L145

Hi! 
There is a limitaion on using files that ends with ".jar". Would it be possible to extend it to files that ends with ".jar.original" as spring boot generates non fat-jar having this default name pattern?
If it's possible for you, I can create a MR.

Thanks

**Comment by bluebreezecf** [comment]
@elzinko  I appreciate for your advice, and it sounds good to your advice.
You can send a MR, and i will check it.

**Comment by elzinko** [comment]
done!

**Comment by bluebreezecf** [comment]
@elzinko  Thanks man, #21 has been merged, so this issue is closed.
Be sure to update to the latest code.
