### ISSUE TITLE
uploadSparkJobJar corrupts file when uploading

### ISSUE THREAD

**Issue by jorisdeveirman** [bluebreezecf/SparkJobServerClient#4]
When using then `ISparkJobServerClient.uploadSparkJobJar(File jarFile, String appName)` method the jar ends up corrupt on the Spark Job Server.
Investigating `SparkJobServerClientImpl.uploadSparkJobJar(InputStream jarData, String appName)` confirms this. Reading bytes and saving them in a StringBuffer screws up the bytes.

I considered following implementation and found it working:

```
FileEntity fileEntity = new FileEntity(file)
httppost.setEntity(fileEntity);
HttpResponse response = httpClient.execute(httppost);
```

Alternative for Inputstream you can use `InputStreamEntity`.

**Comment by bluebreezecf** [comment]
@jorisdeveirman 
Maybe in your scene, the uploaded jar file is much bigger.
Thanks for your advice. Perhaps, you can submit a PR to fix this bug.
BR.

**Comment by jwestra** [comment]
Having the same issue with a Jar that is only 3 KB.  It becomes corrupt on the transfer.  Joris, I see you did not do a PR.  Can you at least share the code another way, if you have it working?

**Comment by yatszhash** [comment]
I met the same issue (main wasn't found in classpath with the uploaded jar).
I fix it by change the method to binarize jar.

**Comment by yatszhash** [comment]
PR #12

**Comment by bluebreezecf** [comment]
@jorisdeveirman  @jwestra 
Update the latest code to see if it is ok now.

**Comment by yatszhash** [comment]
thanks a lot for merge

**Comment by bluebreezecf** [comment]
@yatszhash Thanks a lot for this contribution!
