### ISSUE TITLE
Attaching the example jar.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [bluebreezecf/SparkJobServerClient#5]
Hi,

Its a very good initiative. Can you please attach the spark-examples_2.10-1.0.2.jar. With the code.
It will be helpful for beginner like me.

Right now i am facing some issue. which i am not able to track. your jar will give some starting point for me.

org.khaleesi.carfield.tools.sparkjobserver.api.SparkJobServerClientException: Spark Job Server http://localhost:8090/ response 404 {
  "status": "ERROR",
  "status": "ERROR",
  "result": "classPath com.oreilly.learningsparkexamples.mini.java.WordCount not found"
  "result": "classPath com.oreilly.learningsparkexamples.mini.java.WordCount not found"
}
}
    at org.khaleesi.carfield.tools.sparkjobserver.api.SparkJobServerClientImpl.logError(SparkJobServerClientImpl.java:461)
    at org.khaleesi.carfield.tools.sparkjobserver.api.SparkJobServerClientImpl.startJob(SparkJobServerClientImpl.java:302)
    at org.khaleesi.carfield.tools.sparkjobserver.api.SparkJobServerClientTest.main(SparkJobServerClientTest.java:65)

**Comment by bradfordwagner** [comment]
This is an issue with not having WordCount in your JobServer's class path. If you want to run the word count example, I would suggest using spark shell. If you want to run it inside of a SparkJobServer then you would have to create a SparkJob that uses the example.

**Comment by jamalahmedmaaz** [comment]
Thanks. Please close the issue.
